version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: camprent-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db_camprent
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
